name: .NET Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      working-directory: PersianTools.Core/PersianTools.Core
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
      working-directory: PersianTools.Core/PersianTools.Core
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
      working-directory: PersianTools.Core/PersianTools.Core
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
      working-directory: PersianTools.Core/PersianTools.Core
    - name: Push
      run: dotnet nuget push PersianTools.Core.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${GITHUB_TOKEN}
      working-directory: PersianTools.Core/PersianTools.Core
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
